-- CRIAR ENTIDADE DEPARTAMENTO
CREATE TABLE DEPARTAMENTOS(
	ID_DEPARTAMENTO INT PRIMARY KEY,
	SIGLA_DEPARTAMENTO VARCHAR(3) NOT NULL,
	NOME_DEPARTAMENTO VARCHAR(30) NOT NULL 
);

-- VISUALIZA A ENTIDADE CRIADA
SELECT * FROM DEPARTAMENTOS;

CREATE TABLE CURSOS(
	ID_CURSO INT PRIMARY KEY,
	ID_DEPARTAMENTO INT REFERENCES DEPARTAMENTOS,
	SIGLA_CURSO VARCHAR(3) NOT NULL,
	NOME_CURSO VARCHAR(30) NOT NULL 
);

CREATE TABLE CURSOS(
	ID_CURSO INT PRIMARY KEY,
	ID_DEPARTAMENTO INT REFERENCES DEPARTAMENTOS,
	SIGLA_CURSO VARCHAR(3) NOT NULL,
	NOME_CURSO VARCHAR(30) NOT NULL 
);

-- ALTERA O TAMANHO DO VARCHAR
ALTER TABLE CURSOS ALTER COLUMN NOME_CURSO TYPE VARCHAR(50);

-- VISUALIZA A ENTIDADE CRIADA
SELECT * FROM CURSOS;


CREATE TABLE DISCIPLINAS(
	ID_DISCIPLINA INT PRIMARY KEY,
	ID_CURSO INT REFERENCES CURSOS,
	SIGLA_DISCIPLINA VARCHAR(4) NOT NULL,
	NOME_DISCIPLINA VARCHAR(50),
	OPTATIVA BOOLEAN DEFAULT FALSE
);

-- VISUALIZA A ENTIDADE CRIADA
SELECT * FROM DISCIPLINAS;


CREATE TABLE ALUNOS(
	RA INT PRIMARY KEY,
	CPF VARCHAR(14) NOT NULL UNIQUE,
	NOME_ALUNO VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO DATE CHECK(AGE(CURRENT_DATE,DATA_NASCIMENTO)>='14'),
	STATUS BOOLEAN DEFAULT TRUE
);

-- VISUALIZA A ENTIDADE CRIADA
SELECT * FROM ALUNOS;

CREATE TABLE DISCIPLINA_ALUNOS(
	ID_DISCIPLINA_ALUNO INT PRIMARY KEY,
	ID_DISCIPLINA INT REFERENCES DISCIPLINAS,
	RA INT REFERENCES ALUNOS,
	DATA_MATRICULA DATE
)

SELECT * FROM DISCIPLINA_ALUNOS;